import { Post, PostService } from 'marcioasan-sdk'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import FeaturedPost from '../components/FeaturedPost'

interface HomeProps {
  posts: Post.Paginated;
}

export default function Home(props: HomeProps) {
  const { posts } = props;
  return (
    <div>
      <Head>
        <title>Alganews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        posts?.content && <FeaturedPost postSummary={posts?.content[0]}
      />
      }
    </div>
  )
}

//11.23. Recuperando parâmetros da Query String
export const getServerSideProps: GetServerSideProps<HomeProps> = async (context) => {
  const { page } = context.query;
  const posts = await PostService.getAllPosts({ page: Number(page) - 1 });

  return {
    props: {
      posts,
    },
  };
};



//11.22. getServerSideProps vs useEffect
// export async function getServerSideProps() {
//   const posts = await PostService.getAllPosts({ page: 0 });
//   return {
//     props: {
//       posts,
//     },
//   };
// }